-- UAE-focused FAQ seed (generated by scripts/generate-faq-seed-sql.mjs)
begin;

insert into public.faq_topics (id, slug, title, sort_order, published) values
  ('10000000-0000-4000-8000-000000000001', 'buying-dubai-uae', 'Buying property in Dubai & the UAE', 0, true),
  ('10000000-0000-4000-8000-000000000002', 'renting-uae', 'Renting in the UAE', 1, true),
  ('10000000-0000-4000-8000-000000000003', 'golden-visa-residency', 'Golden Visa & UAE residency', 2, true),
  ('10000000-0000-4000-8000-000000000004', 'mortgages-finance-uae', 'Mortgages & UAE property finance', 3, true),
  ('10000000-0000-4000-8000-000000000005', 'off-plan-new-developments', 'Off-plan & new developments', 4, true),
  ('10000000-0000-4000-8000-000000000006', 'dld-title-legal', 'DLD, title & legal essentials', 5, true),
  ('10000000-0000-4000-8000-000000000007', 'fees-service-charges-noc', 'Fees, service charges & NOC', 6, true),
  ('10000000-0000-4000-8000-000000000008', 'dubai-neighbourhoods', 'Dubai neighbourhoods & lifestyle', 7, true),
  ('10000000-0000-4000-8000-000000000009', 'abu-dhabi-other-emirates', 'Abu Dhabi & other emirates', 8, true),
  ('10000000-0000-4000-8000-00000000000a', 'investment-roi-strategy', 'Investment strategy & ROI in the UAE', 9, true),
  ('10000000-0000-4000-8000-00000000000b', 'selling-listing-home', 'Selling & listing your UAE home', 10, true),
  ('10000000-0000-4000-8000-00000000000c', 'capital-dream-services', 'Working with Capital Dream', 11, true)
  on conflict (slug) do nothing;

insert into public.faq_entries (id, topic_id, question, answer, sort_order, published) values
  ('00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', $f$Can foreigners buy freehold property in Dubai?$f$, $f$Yes. Many communities in Dubai are designated freehold, allowing non-UAE nationals to own outright subject to Dubai Land Department (DLD) rules and developer or master community requirements. Capital Dream helps you shortlist assets that match your residency status, budget, and holding structure before you commit.

Freehold ownership is not universal across every plot in the UAE, so verification on the title and permitted use is essential.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001', $f$What is the difference between freehold and leasehold in the UAE?$f$, $f$Freehold typically grants ownership of the unit (and often a share of common land) for an indefinite period, while leasehold means you hold rights for a fixed term (commonly decades) from a master lessor. The practical impact shows up in financing, resale appetite, and renewal terms.

Capital Dream explains how each structure affects your exit plan and running costs for Dubai and wider UAE assets.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000001', $f$What are the main steps to buy a resale villa or apartment in Dubai?$f$, $f$A typical resale path includes agreeing commercial terms, signing a Form F (MOU) with clear conditions, buyer due diligence on title and seller authority, securing mortgage approval if needed, and completing transfer at a DLD trustee office with settlement of fees.

Capital Dream coordinates timelines, documentation, and handover so surprises are minimized.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000001', $f$How long does a Dubai property transfer usually take?$f$, $f$Cash purchases with clean title and no mortgage can sometimes complete in a matter of days once parties are aligned. Mortgaged transactions or complex corporate buyers may take longer while banks and compliance checks run in parallel.

Your Capital Dream advisor will map a realistic schedule based on your specific case.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000005', '10000000-0000-4000-8000-000000000001', $f$What is Oqood registration and when does it apply?$f$, $f$Oqood is the DLD system used to register off-plan sales contracts, helping protect buyer interests while the project is under construction. It is a key milestone before eventual title issuance upon completion.

If you are buying off-plan, Capital Dream ensures you understand payment plans, registration milestones, and handover requirements.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000006', '10000000-0000-4000-8000-000000000001', $f$Can I buy UAE property through a company?$f$, $f$Corporate holding is common for certain investors, but eligibility, licensing, and bank lending rules differ from personal purchases. The right structure depends on tax residency, estate planning, and whether you need a mortgage.

Capital Dream works with your legal and tax advisers to align the purchase vehicle with your goals.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000007', '10000000-0000-4000-8000-000000000001', $f$Which documents do buyers typically need in Dubai?$f$, $f$Expect passport copies, Emirates ID where applicable, proof of funds or a mortgage pre-approval, and any corporate resolutions if a company is buying. Sellers must provide clear title and NOCs where required by the developer or master community.

Capital Dream provides a checklist tailored to your transaction type.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000008', '10000000-0000-4000-8000-000000000001', $f$Should I get mortgage pre-approval before making an offer?$f$, $f$Pre-approval strengthens your negotiating position and prevents wasted time on homes outside bank parameters. UAE lenders assess income, liabilities, and the specific asset.

Capital Dream can introduce mortgage specialists and align your offer strategy with realistic lending limits.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000009', '10000000-0000-4000-8000-000000000001', $f$What is a Form F in Dubai resale transactions?$f$, $f$Form F is the standard memorandum of understanding used for resale deals, recording price, deposit, timelines, and conditions. It should be reviewed carefully alongside agency agreements.

Capital Dream ensures your paperwork reflects what was agreed commercially and protects your deposit conditions.$f$, 8, true),
  ('00000000-0000-4000-8000-00000000000a', '10000000-0000-4000-8000-000000000001', $f$Are escrow accounts required for off-plan purchases in Dubai?$f$, $f$Dubai’s regulatory framework uses project escrow mechanisms so buyer funds for registered off-plan sales are ring-fenced for construction in line with applicable rules. Always confirm registration status and escrow compliance for the specific project.

Capital Dream prioritizes developer track record and regulatory posture in every shortlist.$f$, 9, true),
  ('00000000-0000-4000-8000-00000000000b', '10000000-0000-4000-8000-000000000002', $f$How are rental contracts registered in Dubai?$f$, $f$Long-term Dubai leases are typically registered through Ejari, which formalizes the tenancy for utilities, visas, and dispute processes. Registration should align with RERA guidelines and agreed rent.

Capital Dream helps landlords and tenants understand documentation before move-in.$f$, 0, true),
  ('00000000-0000-4000-8000-00000000000c', '10000000-0000-4000-8000-000000000002', $f$What is the typical rent payment structure in Dubai?$f$, $f$Many landlords request one to four cheques per year, though terms vary by community and asset class. Corporate lets may differ.

Capital Dream negotiates payment schedules that balance landlord security with tenant cash flow.$f$, 1, true),
  ('00000000-0000-4000-8000-00000000000d', '10000000-0000-4000-8000-000000000002', $f$Can landlords increase rent every year in Dubai?$f$, $f$Increases must follow the applicable rent index and notice rules for renewals in Dubai. Disputes can be taken to the Rental Dispute Center when parties disagree.

Speak with Capital Dream for a market read before you renew or repricing a listing.$f$, 2, true),
  ('00000000-0000-4000-8000-00000000000e', '10000000-0000-4000-8000-000000000002', $f$What fees do tenants pay when moving in?$f$, $f$Tenants may pay a security deposit, agency fee where applicable, Ejari and utility deposits, and chiller or cooling charges depending on the building. Always read the addendum for service charges passed through.

Capital Dream clarifies the full move-in cost stack before you sign.$f$, 3, true),
  ('00000000-0000-4000-8000-00000000000f', '10000000-0000-4000-8000-000000000002', $f$Is short-term letting allowed in every Dubai community?$f$, $f$Short-term holiday letting is regulated; many master communities restrict or prohibit platforms unless licensed and permitted. Violations can affect owners and tenants.

Capital Dream advises on compliant strategies if you are an investor targeting hospitality yields.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000010', '10000000-0000-4000-8000-000000000002', $f$What happens if a tenant breaks a lease early?$f$, $f$Early termination depends on your contract clauses, notice period, and whether a landlord can mitigate loss by re-letting. Some contracts include a fixed penalty.

Capital Dream recommends clear exit terms upfront for both parties.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000011', '10000000-0000-4000-8000-000000000002', $f$Do I need a housing allowance letter to rent?$f$, $f$Employers sometimes provide letters for corporate relocations, but private landlords mainly care about affordability, references, and security deposits. Banks may ask for more if you are structuring payments.

Capital Dream streamlines tenant packs for competitive listings.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000012', '10000000-0000-4000-8000-000000000002', $f$Are pets allowed in Dubai rentals?$f$, $f$Pet policies are set by landlords and building rules; some towers prohibit pets entirely. Always get written approval.

Capital Dream matches pet owners to realistic buildings to avoid move-in conflicts.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000013', '10000000-0000-4000-8000-000000000002', $f$How do utilities and DEWA work for new tenants?$f$, $f$Tenants usually activate DEWA in their name with Ejari and pay deposits. District cooling providers may be separate.

Capital Dream provides a utility checklist for a smooth handover.$f$, 8, true),
  ('00000000-0000-4000-8000-000000000014', '10000000-0000-4000-8000-000000000002', $f$What is the difference between furnished and unfurnished rent in the UAE?$f$, $f$Furnished homes command higher rents and shorter average tenancies; unfurnished suits longer stays and personalisation. Inventory condition should be photo-documented.

Capital Dream prices listings competitively for the chosen furnishing strategy.$f$, 9, true),
  ('00000000-0000-4000-8000-000000000015', '10000000-0000-4000-8000-000000000003', $f$Can buying UAE property help with long-term residency?$f$, $f$The UAE offers long-term visa categories tied to qualifying investments, including property thresholds that authorities may update. Eligibility depends on value, title status, and program rules at the time of application.

Capital Dream points you to qualified immigration counsel and aligns property choices with your visa goals.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000016', '10000000-0000-4000-8000-000000000003', $f$What property value is referenced for investor visas?$f$, $f$Published thresholds and eligible asset types can change; approvals also consider whether the property is mortgaged and the equity you hold. Always verify current federal and emirate guidance.

Capital Dream focuses on assets with clean title and documentation that support a smooth application file.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000017', '10000000-0000-4000-8000-000000000003', $f$Does a mortgage affect Golden Visa eligibility?$f$, $f$Mortgages can affect how authorities assess net investment; some programs look at paid-up value rather than headline price. Lender and DLD records must be consistent.

Your Capital Dream advisor coordinates with your mortgage bank and legal team on the narrative.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000018', '10000000-0000-4000-8000-000000000003', $f$Can off-plan purchases count toward residency investment rules?$f$, $f$Rules evolve and may distinguish between registered off-plan contracts and completed title. The status of construction and registration matters.

Capital Dream highlights completion risk and documentation when residency timing is critical.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000019', '10000000-0000-4000-8000-000000000003', $f$How long do UAE long-term visas last?$f$, $f$Many investor-linked visas are issued for extended periods and are renewable subject to continued compliance with program conditions. Medical insurance and security checks are part of the cycle.

Capital Dream supports clients who relocate alongside a property purchase.$f$, 4, true),
  ('00000000-0000-4000-8000-00000000001a', '10000000-0000-4000-8000-000000000003', $f$Do family members qualify under investor visas?$f$, $f$Dependent sponsorship rules exist for spouses and children within defined frameworks, with documentation requirements. Domestic worker sponsorship follows separate rules.

Capital Dream connects you with specialists for household relocation planning.$f$, 5, true),
  ('00000000-0000-4000-8000-00000000001b', '10000000-0000-4000-8000-000000000003', $f$Is a Golden Visa the same as tax residency?$f$, $f$No. UAE visa status is separate from how other countries tax you on worldwide income. You should obtain personal tax advice in every relevant jurisdiction.

Capital Dream stays focused on real estate while your accountants define tax posture.$f$, 6, true),
  ('00000000-0000-4000-8000-00000000001c', '10000000-0000-4000-8000-000000000003', $f$What documents from a property purchase support a visa file?$f$, $f$Expect title or Oqood extracts, purchase contracts, payment evidence, and NOCs as required by the authority reviewing the file. Translations may be needed.

Capital Dream helps assemble a coherent property evidence pack.$f$, 7, true),
  ('00000000-0000-4000-8000-00000000001d', '10000000-0000-4000-8000-000000000003', $f$Can I lose my visa if I sell the qualifying property?$f$, $f$Program rules tie renewal to continued satisfaction of investment conditions. Selling may affect renewal unless you reinvest in another qualifying asset in time.

Plan exits with Capital Dream before you list.$f$, 8, true),
  ('00000000-0000-4000-8000-00000000001e', '10000000-0000-4000-8000-000000000003', $f$Where should I verify the latest UAE visa rules?$f$, $f$Official portals and licensed immigration consultants are the sources of truth; blogs quickly go out of date.

Capital Dream provides property-side diligence while your GDRFA-approved PRO handles submissions.$f$, 9, true),
  ('00000000-0000-4000-8000-00000000001f', '10000000-0000-4000-8000-000000000004', $f$Can expats get mortgages for Dubai property?$f$, $f$Yes, many UAE banks lend to employed expats and some self-employed profiles, subject to income proof, stress tests, and loan-to-value limits that differ for residents vs non-residents.

Capital Dream pairs you with mortgage advisors who understand your employer type and currency of income.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000020', '10000000-0000-4000-8000-000000000004', $f$What loan-to-value (LTV) limits apply in the UAE?$f$, $f$Central Bank rules set maximum LTV bands for first and subsequent properties and for completed vs under-construction homes. Banks may be stricter than the ceiling.

Capital Dream models your deposit requirement before you offer.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000021', '10000000-0000-4000-8000-000000000004', $f$Are interest rates fixed or variable for UAE home loans?$f$, $f$Products include fixed-rate windows, variable spreads over benchmarks, and hybrid structures. Early settlement fees and conversion charges vary.

Capital Dream encourages a side-by-side comparison of total cost over your holding period.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000022', '10000000-0000-4000-8000-000000000004', $f$How does the bank value the property I want to buy?$f$, $f$Lenders instruct panel valuers who assess market evidence, asset condition, and sometimes developer discounts. A low valuation can reduce the loan amount.

Capital Dream anticipates valuation gaps on secondary listings.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000023', '10000000-0000-4000-8000-000000000004', $f$Can I finance service charges and DLD fees?$f$, $f$Mortgages generally finance the property purchase price or bank-approved valuation, not ongoing fees. Budget transfer and agency costs in cash.

Capital Dream provides a full funds-needed table for closing.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000024', '10000000-0000-4000-8000-000000000004', $f$What is life insurance requirement for UAE mortgages?$f$, $f$Many banks require property insurance and borrower life coverage assigned to the lender. Premiums affect your monthly outflow.

Capital Dream factors insurance into affordability.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000025', '10000000-0000-4000-8000-000000000004', $f$Can non-residents borrow against Dubai real estate?$f$, $f$Some banks lend to non-residents with higher down payments and narrower lists of approved projects. Compliance checks can be more intensive.

Capital Dream targets bankable assets for international buyers.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000026', '10000000-0000-4000-8000-000000000004', $f$How does remortgaging or equity release work?$f$, $f$Refinancing can release equity or improve pricing if your profile and valuations support it. Exit penalties on the old loan matter.

Capital Dream reviews whether a refinance suits your investment horizon.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000027', '10000000-0000-4000-8000-000000000004', $f$Do Islamic finance options exist for UAE property?$f$, $f$Islamic banks offer Sharia-compliant structures such as diminishing musharakah with documented mechanics. Pricing should be compared transparently to conventional alternatives.

Capital Dream introduces both conventional and Islamic desks where needed.$f$, 8, true),
  ('00000000-0000-4000-8000-000000000028', '10000000-0000-4000-8000-000000000004', $f$What slows mortgage approval most often?$f$, $f$Incomplete salary certificates, variable bonus treatment, employer in unusual jurisdictions, or title quirks on older villas. Valuation shortfalls also pause deals.

Capital Dream pre-vets files to reduce last-minute surprises.$f$, 9, true),
  ('00000000-0000-4000-8000-000000000029', '10000000-0000-4000-8000-000000000005', $f$Why do investors choose Dubai off-plan property?$f$, $f$Payment plans, developer incentives, and potential capital growth before completion attract buyers who accept construction and market timing risk.

Capital Dream differentiates between trophy launches and fundamentals-driven buys.$f$, 0, true),
  ('00000000-0000-4000-8000-00000000002a', '10000000-0000-4000-8000-000000000005', $f$What should I check in a sales purchase agreement (SPA)?$f$, $f$Review payment schedule, late payment clauses, completion date mechanics, variation rights, defect liability, and cancellation remedies. Escrow and registration steps should be explicit.

Capital Dream recommends independent legal review of every SPA.$f$, 1, true),
  ('00000000-0000-4000-8000-00000000002b', '10000000-0000-4000-8000-000000000005', $f$What is a snagging inspection?$f$, $f$Before handover, a snagging report lists finishing defects for the developer to rectify. Quality varies by contractor and project tier.

Capital Dream advises professional snagging for premium finishes.$f$, 2, true),
  ('00000000-0000-4000-8000-00000000002c', '10000000-0000-4000-8000-000000000005', $f$Can I sell my off-plan contract before completion?$f$, $f$Some developers allow assignment to a new buyer subject to fees and eligibility. The developer’s consent process matters.

Capital Dream explains assignment economics before you sign.$f$, 3, true),
  ('00000000-0000-4000-8000-00000000002d', '10000000-0000-4000-8000-000000000005', $f$How do payment plans typically work?$f$, $f$Plans may combine down payment, construction-linked instalments, and post-handover cheques. Cost of capital differs from mortgages.

Capital Dream models IRR and cash flow alongside alternative investments.$f$, 4, true),
  ('00000000-0000-4000-8000-00000000002e', '10000000-0000-4000-8000-000000000005', $f$What is the risk if a project delays?$f$, $f$Delays affect rent start dates, mortgage drawdowns, and personal plans. Contract clauses define relief and notices.

Capital Dream weighs developer delivery track record in every recommendation.$f$, 5, true),
  ('00000000-0000-4000-8000-00000000002f', '10000000-0000-4000-8000-000000000005', $f$Are post-handover payment plans always a good deal?$f$, $f$They improve short-term cash flow but may embed a price premium or restrict resale until certain thresholds are paid.

Capital Dream reads the fine print with you.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000030', '10000000-0000-4000-8000-000000000005', $f$How do service charges get estimated off-plan?$f$, $f$Developers publish indicative service charges that can change once owners’ associations finalize budgets. High charges erode net yields.

Capital Dream stress-tests yields with conservative service charge assumptions.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000031', '10000000-0000-4000-8000-000000000005', $f$Should I buy directly from developer or resale in a new community?$f$, $f$Developer sales may offer better plans; resale may show a completed product with known defects and real rents.

Capital Dream compares net outcomes for your timeline.$f$, 8, true),
  ('00000000-0000-4000-8000-000000000032', '10000000-0000-4000-8000-000000000005', $f$What warranties apply after handover?$f$, $f$Defect liability periods and structural warranties depend on the SPA and local consumer protection frameworks. Keep correspondence in writing.

Capital Dream documents handover condition for investor clients.$f$, 9, true),
  ('00000000-0000-4000-8000-000000000033', '10000000-0000-4000-8000-000000000006', $f$What does Dubai Land Department (DLD) do in a sale?$f$, $f$DLD registers ownership transfers, collects transfer fees, and maintains the official record of title for registered properties. Trustee centers execute many steps.

Capital Dream schedules transfers so funds and documents align.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000034', '10000000-0000-4000-8000-000000000006', $f$How do I verify a seller truly owns the property?$f$, $f$Request a recent title deed or official ownership extract and match passport names, unit numbers, and any mortgage notes. For corporate sellers, verify signatories.

Capital Dream treats title verification as non-negotiable.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000035', '10000000-0000-4000-8000-000000000006', $f$What is a no-objection certificate (NOC) from a developer?$f$, $f$Developers issue NOCs confirming no outstanding amounts before DLD transfer in many communities. Fees and processing times vary.

Capital Dream tracks NOC status to avoid blocked transfer dates.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000036', '10000000-0000-4000-8000-000000000006', $f$Can there be restrictions on resale?$f$, $f$Some SPAs or master community rules impose lock-in periods or resale fees for off-plan and occasionally resale units.

Capital Dream surfaces restrictions early in underwriting.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000037', '10000000-0000-4000-8000-000000000006', $f$What is a usufruct or long lease right?$f$, $f$Some structures grant long-term use rights rather than classic freehold; financing and resale differ.

Capital Dream explains how the right appears on title searches.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000038', '10000000-0000-4000-8000-000000000006', $f$Do I need a POA to buy remotely?$f$, $f$Many buyers use notarized powers of attorney for signing and transfer steps. Banks and DLD have formatting requirements.

Capital Dream coordinates templates with your lawyer.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000039', '10000000-0000-4000-8000-000000000006', $f$How are jointly owned properties handled?$f$, $f$Co-owners should agree share splits, mortgage liability, and exit mechanics up front. DLD registration should mirror the agreement.

Capital Dream flags governance questions for joint buyers.$f$, 6, true),
  ('00000000-0000-4000-8000-00000000003a', '10000000-0000-4000-8000-000000000006', $f$What happens if there is an active mortgage on the seller’s unit?$f$, $f$The seller’s bank must clear the liability and release the mortgage note as part of settlement, often via a blocking arrangement.

Capital Dream works with conveyancing teams on simultaneous closure.$f$, 7, true),
  ('00000000-0000-4000-8000-00000000003b', '10000000-0000-4000-8000-000000000006', $f$Are verbal promises from agents binding?$f$, $f$Only written contract terms and registered instruments typically count. Marketing brochures may disclaim liability.

Capital Dream documents material representations through the right channels.$f$, 8, true),
  ('00000000-0000-4000-8000-00000000003c', '10000000-0000-4000-8000-000000000006', $f$When should I hire a UAE real estate lawyer?$f$, $f$Complex corporate purchases, bulk deals, distressed assignments, and unusual title histories merit counsel. Even standard buys benefit from Form F review.

Capital Dream integrates legal review into premium transactions.$f$, 9, true),
  ('00000000-0000-4000-8000-00000000003d', '10000000-0000-4000-8000-000000000007', $f$What is the Dubai land transfer fee for buyers?$f$, $f$Transfer fees are a percentage of the sale price (subject to floors/ceilings that DLD may adjust); small administrative charges also apply. Budget agency fees separately if you use a broker.

Capital Dream gives a closing cost estimate before you commit.$f$, 0, true),
  ('00000000-0000-4000-8000-00000000003e', '10000000-0000-4000-8000-000000000007', $f$Who pays the real estate agent commission?$f$, $f$Market practice varies between landlord-paid, tenant-paid, or seller-paid models depending on emirate norms and mandates. Your agreement should state it clearly.

Capital Dream explains the mandate you are signing.$f$, 1, true),
  ('00000000-0000-4000-8000-00000000003f', '10000000-0000-4000-8000-000000000007', $f$What are typical service charges in Dubai towers?$f$, $f$Charges depend on amenities, chiller inclusion, staff levels, and insurance. Luxury towers can run materially higher per sq ft than mid-market stock.

Capital Dream compares buildings on a total-cost basis.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000040', '10000000-0000-4000-8000-000000000007', $f$Are cooling charges separate from DEWA?$f$, $f$Many master communities use district cooling providers billed separately from electricity. Arrears can block seller NOCs.

Capital Dream checks utility clearance before transfer.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000041', '10000000-0000-4000-8000-000000000007', $f$What is a seller NOC fee?$f$, $f$Developers may charge an NOC processing fee and require settlement of service charge arrears. Amounts differ by community.

Capital Dream models seller net proceeds after NOC and mortgage settlement.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000042', '10000000-0000-4000-8000-000000000007', $f$Do I pay VAT on residential resale?$f$, $f$VAT treatment depends on whether supply is residential, first supply, commercial, or mixed-use, and on registration status. Get accounting advice for edge cases.

Capital Dream focuses on documented transaction costs you will see at closing.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000043', '10000000-0000-4000-8000-000000000007', $f$What is the trustee office administration fee?$f$, $f$Trustee centers charge for processing DLD appointments and paperwork bundles. It is separate from DLD transfer fee.

Capital Dream includes trustee costs in buyer cash calls.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000044', '10000000-0000-4000-8000-000000000007', $f$Are there penalties for late registration of tenancy?$f$, $f$Ejari and municipal rules may impose fines or block certain services if registration lags. Compliance protects both parties.

Capital Dream prompts timely registration for managed lets.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000045', '10000000-0000-4000-8000-000000000007', $f$How often do owners’ associations increase budgets?$f$, $f$OA boards review insurance, utilities, and maintenance annually; special assessments can follow major repairs.

Capital Dream reviews OA minutes when available for investment stock.$f$, 8, true),
  ('00000000-0000-4000-8000-000000000046', '10000000-0000-4000-8000-000000000007', $f$What hidden costs surprise first-time UAE buyers?$f$, $f$Mortgage arrangement fees, valuation fees, life insurance premiums, moving and fit-out, and short-term rent overlap add up.

Capital Dream uses a total landing cost worksheet with every purchase plan.$f$, 9, true),
  ('00000000-0000-4000-8000-000000000047', '10000000-0000-4000-8000-000000000008', $f$Is Dubai Marina still a strong rental market?$f$, $f$Marina remains liquid with international tenant demand, though yields compress when prices rise. View, tower quality, and parking drive spreads.

Capital Dream underwrites Marina units with micro-location detail.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000048', '10000000-0000-4000-8000-000000000008', $f$What defines Palm Jumeirah premium pricing?$f$, $f$Frond versus trunk positioning, private pool, beach access, and hotel branding all matter. Maintenance and service levels are high.

Capital Dream matches Palm inventory to lifestyle and capital preservation goals.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000049', '10000000-0000-4000-8000-000000000008', $f$Are Downtown Dubai yields lower than outer communities?$f$, $f$Prime central locations often trade yield for liquidity and brand. Compare net income after service charges.

Capital Dream benchmarks Downtown against Business Bay and DIFC micro-markets.$f$, 2, true),
  ('00000000-0000-4000-8000-00000000004a', '10000000-0000-4000-8000-000000000008', $f$Is Arabian Ranches suited for family buyers?$f$, $f$Low-rise villas with schools and community facilities appeal to long-tenure families. Commute patterns matter.

Capital Dream maps school and office routes for relocating households.$f$, 3, true),
  ('00000000-0000-4000-8000-00000000004b', '10000000-0000-4000-8000-000000000008', $f$What is driving demand in Dubai Hills Estate?$f$, $f$Golf course amenity, mall access, and newer stock attract end-users and investors. Supply waves can affect near-term pricing.

Capital Dream tracks launch pipelines alongside resale stock.$f$, 4, true),
  ('00000000-0000-4000-8000-00000000004c', '10000000-0000-4000-8000-000000000008', $f$How should I compare JVC versus JVT?$f$, $f$Both offer dense mid-rise stock at accessible price points; build quality, parking, and traffic patterns differ by cluster.

Capital Dream visits clusters physically before you bid.$f$, 5, true),
  ('00000000-0000-4000-8000-00000000004d', '10000000-0000-4000-8000-000000000008', $f$Is DIFC only for apartments?$f$, $f$DIFC is predominantly luxury apartments with strong professional tenancy. Rules around use and short lets are strict.

Capital Dream aligns DIFC buys with compliance and tenant type.$f$, 6, true),
  ('00000000-0000-4000-8000-00000000004e', '10000000-0000-4000-8000-000000000008', $f$What about waterfront communities beyond Palm?$f$, $f$Mina Rashid, Creek Harbour, and Emaar Beachfront offer alternative waterfront narratives with different completion profiles.

Capital Dream contrasts delivery risk and view permanence.$f$, 7, true),
  ('00000000-0000-4000-8000-00000000004f', '10000000-0000-4000-8000-000000000008', $f$Do branded residences outperform non-branded?$f$, $f$Branding can support nightly rates and global recognition but may carry higher fees. Performance is project-specific.

Capital Dream evaluates branded inventory case by case.$f$, 8, true),
  ('00000000-0000-4000-8000-000000000050', '10000000-0000-4000-8000-000000000008', $f$How does Expo City and south Dubai fit an investment map?$f$, $f$Infrastructure and event legacy support certain demand drivers; distance from traditional office cores influences tenancy.

Capital Dream tests south Dubai theses against your holding period.$f$, 9, true),
  ('00000000-0000-4000-8000-000000000051', '10000000-0000-4000-8000-000000000009', $f$Can foreigners buy in Abu Dhabi freehold areas?$f$, $f$Abu Dhabi expanded investment zones where non-GCC nationals can acquire defined property rights; rules differ from Dubai. Verify zone eligibility and title type.

Capital Dream coordinates with local partners for Abu Dhabi diligence.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000052', '10000000-0000-4000-8000-000000000009', $f$What is different about buying in Ras Al Khaimah?$f$, $f$RAK offers competitive entry points and hospitality narratives; infrastructure and tenant depth differ from Dubai.

Capital Dream frames RAK as a specialist allocation within a broader UAE portfolio.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000053', '10000000-0000-4000-8000-000000000009', $f$Is Sharjah ownership structure different?$f$, $f$Sharjah historically emphasized usufruct and leasehold models for non-GCC buyers in many projects. Read title carefully.

Capital Dream ensures you understand duration and renewal mechanics.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000054', '10000000-0000-4000-8000-000000000009', $f$How do Ajman and Umm Al Quwain markets compare?$f$, $f$Lower ticket prices can mean thinner resale liquidity and different tenant profiles.

Capital Dream stress-tests exit scenarios for budget emirate stock.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000055', '10000000-0000-4000-8000-000000000009', $f$Can I use a Dubai mortgage to buy in another emirate?$f$, $f$Bank product coverage varies; some lenders emirate-limit approvals or apply different LTVs.

Capital Dream confirms bankability before you pay booking deposits.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000056', '10000000-0000-4000-8000-000000000009', $f$Are service charges lower outside Dubai?$f$, $f$Not always—new towers with full amenities can charge aggressively anywhere. Compare on a per sq ft basis.

Capital Dream normalizes operating costs across emirates.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000057', '10000000-0000-4000-8000-000000000009', $f$Do tenants follow jobs across emirates?$f$, $f$Commuting patterns and school locations anchor many households; sudden employer moves can increase vacancies in single-industry towns.

Capital Dream reads demographic drivers for each emirate.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000058', '10000000-0000-4000-8000-000000000009', $f$What about Fujairah east coast holiday homes?$f$, $f$Lifestyle and weekend demand differ from metropolitan tenancy; management and maintenance logistics matter.

Capital Dream sets realistic occupancy assumptions.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000059', '10000000-0000-4000-8000-000000000009', $f$Are there UAE-wide property registries?$f$, $f$Each emirate maintains its systems; cross-emirate search is not as unified as a single portal.

Capital Dream conducts emirate-specific title checks.$f$, 8, true),
  ('00000000-0000-4000-8000-00000000005a', '10000000-0000-4000-8000-000000000009', $f$Should my first UAE purchase be Dubai-only?$f$, $f$Many international clients start in Dubai for liquidity, then diversify. Your first buy should match risk tolerance and financing.

Capital Dream builds a phased roadmap when you want multi-emirate exposure.$f$, 9, true),
  ('00000000-0000-4000-8000-00000000005b', '10000000-0000-4000-8000-00000000000a', $f$What gross yield should I expect on a Dubai rental?$f$, $f$Yields vary by community, furnishing, and whether you target long-term or short-term tenants. Advertised yields may ignore vacancy and fees.

Capital Dream models net yield after service charges, management, and insurance.$f$, 0, true),
  ('00000000-0000-4000-8000-00000000005c', '10000000-0000-4000-8000-00000000000a', $f$Is short-term rental always more profitable?$f$, $f$Higher nightly rates come with furnishing cost, platform fees, cleaning, and regulatory compliance. Occupancy volatility rises.

Capital Dream compares stabilized long-term vs managed short-term scenarios.$f$, 1, true),
  ('00000000-0000-4000-8000-00000000005d', '10000000-0000-4000-8000-00000000000a', $f$How do currency moves affect UAE property for UK or EU buyers?$f$, $f$AED is pegged to USD, so GBP and EUR cross rates swing purchase and repatriation value. Hedging is a treasury decision.

Capital Dream illustrates FX sensitivity on your equity.$f$, 2, true),
  ('00000000-0000-4000-8000-00000000005e', '10000000-0000-4000-8000-00000000000a', $f$Should I optimize for capital growth or income?$f$, $f$Prime locations may prioritize growth; mid-market may prioritize yield. Your tax and leverage position influences the answer.

Capital Dream aligns asset class with your mandate.$f$, 3, true),
  ('00000000-0000-4000-8000-00000000005f', '10000000-0000-4000-8000-00000000000a', $f$What is a realistic vacancy assumption?$f$, $f$New towers may need longer lease-up; established communities may re-let faster. Seasonality affects furnished stock.

Capital Dream uses stress vacancies in downside cases.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000060', '10000000-0000-4000-8000-00000000000a', $f$How important is developer brand for resale liquidity?$f$, $f$Recognized developers often attract more bank finance and international buyers, supporting liquidity in downturns.

Capital Dream tracks resale velocity by developer tier.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000061', '10000000-0000-4000-8000-00000000000a', $f$Should I diversify across several small units or one trophy asset?$f$, $f$Diversification reduces single-tenant risk but increases management overhead. Trophy assets can be less liquid in stress.

Capital Dream structures portfolios to match your operating appetite.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000062', '10000000-0000-4000-8000-00000000000a', $f$What tax topics do international investors ask about?$f$, $f$Home-country capital gains, inheritance, and corporate attribution may interact with a UAE purchase. This is not tax advice.

Capital Dream stays in its real estate lane while you consult tax counsel.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000063', '10000000-0000-4000-8000-00000000000a', $f$How do I think about exit timing?$f$, $f$Selling into a strong market with low inventory can help; mortgaged exits need bank coordination. Seasonal listing patterns exist.

Capital Dream times listings with data, not headlines.$f$, 8, true),
  ('00000000-0000-4000-8000-000000000064', '10000000-0000-4000-8000-00000000000a', $f$What role does inflation play in UAE real estate?$f$, $f$Construction costs, wages, and land bids influence replacement value; global liquidity cycles affect demand.

Capital Dream connects macro themes to local micro supply in each submarket.$f$, 9, true),
  ('00000000-0000-4000-8000-000000000065', '10000000-0000-4000-8000-00000000000b', $f$How should I price my Dubai apartment for sale?$f$, $f$Blend recent comparable transactions, current competing listings, and your unit’s differentiators. Overpricing lengthens days-on-market.

Capital Dream prepares evidence-based pricing bands.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000066', '10000000-0000-4000-8000-00000000000b', $f$Should I stage my villa before listing?$f$, $f$Staging can lift photography performance and speed showings for vacant homes. Occupied staging needs decluttering.

Capital Dream recommends staging tiers by price point.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000067', '10000000-0000-4000-8000-00000000000b', $f$What documents should sellers prepare early?$f$, $f$Title, mortgage statements, service charge receipts, DEWA clearances, and tenant Ejari if tenanted. Corporate sellers need board approvals.

Capital Dream runs a seller diligence pack checklist.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000068', '10000000-0000-4000-8000-00000000000b', $f$Can I sell while tenants are in place?$f$, $f$Yes with proper notices and viewing coordination per your tenancy contract and law. Buyers may discount for occupied stock.

Capital Dream manages buyer expectations on handover timing.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000069', '10000000-0000-4000-8000-00000000000b', $f$How do listing portals like Property Finder affect exposure?$f$, $f$Quality media, accurate pricing, and agent responsiveness drive leads on major UAE portals.

Capital Dream optimizes listings for search visibility and conversion.$f$, 4, true),
  ('00000000-0000-4000-8000-00000000006a', '10000000-0000-4000-8000-00000000000b', $f$What is an exclusive vs open listing?$f$, $f$Exclusive mandates align incentives with one brokerage team; open listings can fragment messaging. Fees should match service.

Capital Dream explains mandate economics clearly.$f$, 5, true),
  ('00000000-0000-4000-8000-00000000006b', '10000000-0000-4000-8000-00000000000b', $f$How long do Dubai listings take to sell?$f$, $f$Liquidity varies by tower and price band. Well-priced stock in liquid communities can move quickly; niche homes take longer.

Capital Dream sets realistic timelines from day one.$f$, 6, true),
  ('00000000-0000-4000-8000-00000000006c', '10000000-0000-4000-8000-00000000000b', $f$Should I renovate before selling?$f$, $f$Minor cosmetic refreshes can help; major capex rarely returns 100% unless fixing defects.

Capital Dream advises on highest ROI touch-ups.$f$, 7, true),
  ('00000000-0000-4000-8000-00000000006d', '10000000-0000-4000-8000-00000000000b', $f$What negotiation tactics work in the UAE market?$f$, $f$Clean buyers with bank approvals and flexible transfer dates often win. Deposits and conditionality should be professional.

Capital Dream keeps negotiations transactional and respectful.$f$, 8, true),
  ('00000000-0000-4000-8000-00000000006e', '10000000-0000-4000-8000-00000000000b', $f$How do I handle lowball offers?$f$, $f$Counter with data and motivation context; sometimes silence is strategy. Market heat dictates response.

Capital Dream shields sellers from noise while capturing real buyers.$f$, 9, true),
  ('00000000-0000-4000-8000-00000000006f', '10000000-0000-4000-8000-00000000000c', $f$What does Capital Dream do for UAE property buyers?$f$, $f$We curate shortlists, run pricing diligence, coordinate viewings, introduce mortgage and legal partners, and manage the path to DLD transfer with clear communication.

Our team blends international service standards with on-the-ground UAE execution.$f$, 0, true),
  ('00000000-0000-4000-8000-000000000070', '10000000-0000-4000-8000-00000000000c', $f$Does Capital Dream work with investors outside the UAE?$f$, $f$Yes. We support remote decision-making with video tours, data packs, and POA-friendly processes where appropriate.

Time zones are accommodated for client calls and offer rounds.$f$, 1, true),
  ('00000000-0000-4000-8000-000000000071', '10000000-0000-4000-8000-00000000000c', $f$Can Capital Dream help landlords lease properties?$f$, $f$We advise on pricing, tenant targeting, listing production, and handover documentation for long-term lets.

We align with your property management partner or recommend trusted operators.$f$, 2, true),
  ('00000000-0000-4000-8000-000000000072', '10000000-0000-4000-8000-00000000000c', $f$How does Capital Dream choose which developments to recommend?$f$, $f$We weigh developer track record, location fundamentals, payment plan risk, service charge realism, and your personal mandate—not hype cycles alone.

Conflicts are managed transparently under our mandates.$f$, 3, true),
  ('00000000-0000-4000-8000-000000000073', '10000000-0000-4000-8000-00000000000c', $f$Will Capital Dream negotiate on my behalf?$f$, $f$We represent your interests in offer strategy and counter rounds within the scope of our agency agreement.

Final contract terms are always reviewed with qualified legal counsel.$f$, 4, true),
  ('00000000-0000-4000-8000-000000000074', '10000000-0000-4000-8000-00000000000c', $f$How do I start a consultation with Capital Dream?$f$, $f$Reach out via the site contact channels with your budget range, preferred communities, and timeline. We will confirm a discovery call and next steps.

No obligation until you engage a formal mandate.$f$, 5, true),
  ('00000000-0000-4000-8000-000000000075', '10000000-0000-4000-8000-00000000000c', $f$Does Capital Dream charge buyer fees?$f$, $f$Compensation depends on the transaction type and local brokerage regulations; we disclose fees up front in writing.

You will know what is payable and to whom before you sign.$f$, 6, true),
  ('00000000-0000-4000-8000-000000000076', '10000000-0000-4000-8000-00000000000c', $f$Can Capital Dream coordinate interior design after purchase?$f$, $f$We connect clients with vetted designers and contractors suited to your asset class and budget.

Scope, timelines, and payments remain between you and the supplier.$f$, 7, true),
  ('00000000-0000-4000-8000-000000000077', '10000000-0000-4000-8000-00000000000c', $f$How does Capital Dream handle confidential searches?$f$, $f$We use discreet viewings, NDAs where needed, and controlled information sharing for high-profile clients.

Privacy is a default operating standard.$f$, 8, true),
  ('00000000-0000-4000-8000-000000000078', '10000000-0000-4000-8000-00000000000c', $f$Why choose Capital Dream over a general portal search?$f$, $f$Portals list inventory; we interpret it—pricing traps, building issues, developer history, and negotiation leverage.

You save time and reduce costly mistakes with a guided process.$f$, 9, true),
  ('00000000-0000-4000-8000-000000000079', '10000000-0000-4000-8000-00000000000c', $f$Does Capital Dream support portfolio reviews?$f$, $f$Yes. We can benchmark your existing UAE holdings against current market rents, values, and refinance options.

Investors use us to rebalance across communities and asset types.$f$, 10, true)
  on conflict (id) do nothing;

commit;